build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
     https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
     Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
       throw "There are newer queued builds for this pull request, failing early." }

  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda install conda --channel conda-canary --quiet
  - conda config --add channels conda-forge --force
  - conda install pycryptosat
  - conda config --set sat_solver pycryptosat
  # We cannot use strict on Windows b/c conda refuses to mix defaults::scipy with conda-forge packages.
  # - conda config --set channel_priority strict

  - conda env create --file environment.yml --name IOOS --quiet
  - activate IOOS

test_script:
  - conda info --all
  - conda list
  - python -c "import gdal; print(dir(gdal))"

