repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-added-large-files
      exclude_types: [yaml]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      exclude: docs/source/conf.py
      args: [--max-line-length=105]

- repo: https://github.com/psf/black
  rev: 21.8b0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
    - id: add-trailing-comma
