language: python

sudo: false

env:
  - TEST_TARGET=default
  - TEST_TARGET=notebooks

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes --all
  - conda config --add channels conda-forge --force

install:
  - conda env create environment.yml
  - source activate IOOS
  - conda install flake8 pytest --yes

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100 ;
      find . -type f -name "*.ipynb" | xargs jupyter nbconvert --template=tests/strip_markdown.tpl --stdout --to python | grep -v '^get_ipython' |flake8 - --ignore=W391,E226,E402 --max-line-length=100 --show-source ;
    fi
  - if [[ $TEST_TARGET == 'notebooks' ]]; then
      cd tests && python test_notebooks.py ;
    fi
