build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
     https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
     Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
       throw "There are newer queued builds for this pull request, failing early." }

  # Use the pre-installed Miniconda for the desired arch.
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda update --all --yes
  - "conda-env create -f environment.yml"
  - activate IOOS
  - conda install console_shortcut --yes
  # Fortran cells.
  - conda install -c conda-forge mingwpy --yes
  - set CFG=%CONDA_PREFIX%\Lib\distutils\distutils.cfg
  - echo [build] >> "%CFG%"
  - echo compiler=mingw32 >> "%CFG%"

test_script:
    - cmd: cd tests && python test_notebooks.py
    - cmd: python test_staged_notebooks.py
