name: IOOS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - bagit
  - bokeh
  - cartopy
  - cc-plugin-glider
  - cc-plugin-ncei
  - cftime
  - compliance-checker
  - cython
  - easyargs
  - erddapy
  - flake8
  - geojson
  - geojsonio
  - geolinks
  - geopandas
  - gridgeo
  - hvplot
  - ioos-tools
  - jupyter
  - matplotlib
  - nbdime
  - nc-time-axis
  - nco
  - oceans
  - oct2py
  - palettable
  - phantomjs
  - pocean-core
  - pyoos
  - pyresample
  - pysgrid
  - pytest
  - pyugrid
  - rasterio
  - rise
  - seaborn
  - selenium
  - sensorml2iso
  - siphon
  - spyder
  - sympy
  - thredds_crawler
  - tqdm
  - utide
  - windrose
  - xarray
  - xlrd
  - xmltodict
  # R packages.
  - rpy2
  - r-base=3.5.1
  - r-dt
  - r-finch
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-irkernel
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-robis
  - r-sp
  - r-xtractomatic
  - r-xts
