name: IOOS2
channels:
  - ioos
  - defaults
  - conda-forge
dependencies:
  - icu=56
  - libnetcdf=4.4.0
  - python=2.7
  - anaconda-navigator
  - bagit
  - beautifulsoup4
  - bokeh
  - cartopy
  - cc-plugin-glider
  - cmocean
  - compliance-checker
  - ctd
  - cython
  - descartes
  - fiona
  - flake8
  - folium
  - gdal
  - geojson
  - geojsonio
  - geopandas
  - geos
  - gridgeo
  - gsw
  - iris
  - jsanimation
  - jupyter
  - jupyter_client
  - matplotlib
  - mpld3
  - mplleaflet
  - nb_conda_kernels
  - netcdf4
  - numpy
  - oceans
  - oct2py
  - owslib
  - paegan
  - pandas
  - proj4
  - psutil
  - pygc
  - pykdtree
  - pyoos
  - pyproj
  - pyresample
  - pysgrid
  - pytest
  - pyugrid
  - pyyaml
  - qrcode
  - rasterio
  - rasterstats
  - requests
  - rios
  - rtree
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - shapely
  - siphon
  - spyder
  - statsmodels
  - sympy
  - thredds_crawler
  - xarray
  - xlrd
