name: notebooks_demos
channels:
    - conda-forge
    - ioos
dependencies:
    - python=2.7
    - jupyter
    - iris
    - mpld3
    - pyoos
    - pysgrid
    - pyugrid
    - pyyaml
    - scikit-learn
    - utilities
