target-version = "py312"
line-length = 120
lint.select = [
    "F", # flakes
    "I", # import sorting
    "U", # upgrade
]

lint.ignore = [
    "E402",  # Module level import not at top of file
    ]

# Skipping b/c These notebooks mix R and Python
# NB: nbqa-ruff acts on converted .py so we cannot glob .ipynb :-/
# https://github.com/nbQA-dev/nbQA/issues/823
[lint.extend-per-file-ignores]
"jupyterbook/content/code_gallery/data_access_notebooks/2017-11-30-rerddap*" = [
    "F821",  # Undefined name
]
"jupyterbook/content/code_gallery/data_access_notebooks/2018-02-20-obis*" = [
    "F821",  # Undefined name
]
