name: Build and Deploy docs

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Build environment
      shell: bash -l {0}
      run: |
         conda create --name IOOS --file .binder/conda-linux-64.lock
         source activate IOOS
         conda install doctr

    - name: Build and deploy documentation
      shell: bash -l {0}
      run: |
        set -e
        source activate IOOS
        pushd webpage && python make_index.py && popd
        find notebooks/ -maxdepth 1 -name \*.ipynb -print0 | xargs -0 -n1 jupyter nbconvert --template-file jupyter-jekyll.tpl --config nbconvert_config.py
        # either need to find a GHA to do this or wait until doctr supports GHA
        # python -m doctr deploy --key-path github_deploy_key_ioos_notebooks_demos.enc --built-docs webpage/ .
