name: Build and Deploy docs

on:
  push:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Build environment
      shell: bash -l {0}
      run: |
         conda create --name IOOS --file .binder/conda-linux-64.lock
         source activate IOOS
         conda install doctr
      ## Adding install jupyter{book} command 
         conda install -c conda-forge jupyter-book 

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        source activate IOOS
        pushd webpage && python make_index.py && popd
        find notebooks/ -maxdepth 1 -name \*.ipynb -print0 | xargs -0 -n1 jupyter nbconvert --template-file jupyter-jekyll.tpl --config nbconvert_config.py
      ## Adding jupyter{book} build command 
        jupyter-book build jupyterbook


    ## Adding a GH-Pages deploy option for jupyter{book}
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html