name: Test Environment

on:
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@422500192359a097648154e8db4e39bdb6c6eed7 #v1
        with:
          environment-name: IOOS
          init-shell: bash
          create-args: >-
            --file .binder/conda-lock.yml

      - name: Test environment
        shell: bash -l {0}
        run: |
          python -c 'import osgeo.gdal; print(dir(osgeo.gdal))'
