name: Test Data Access Notebook

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 #v1
        with:
          environment-name: IOOS
          init-shell: bash
          create-args: >-
            --file .binder/conda-lock.yml

      - name: Notebook tests
        shell: bash -l {0}
        run: |
          python -m pytest --nbval --nbval-lax jupyterbook/content/code_gallery/data_access_notebooks/
