name: Test Notebooks

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false

      - name: Build environment
        shell: bash -l {0}
        run: |
          micromamba create --name IOOS --file .binder/conda-linux-64.lock
          micromamba activate IOOS

      - name: Notebook tests
        shell: bash -l {0}
        run: |
          micromamba activate IOOS
          pytest --nbval --nbval-lax jupyterbook/
