name: Build Env on Windows

on:
  pull_request:

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false

      - name: Build environment
        shell: bash -l {0}
        run: |
          micromamba create --name IOOS --file .binder/conda-win-64.lock
          micromamba activate IOOS
          python -c 'import osgeo.gdal; print(dir(osgeo.gdal))'
