name: Test Environment and link rot

on:
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@617811f69075e3fd3ae68ca64220ad065877f246 #v1
        with:
          environment-name: IOOS
          init-shell: bash
          create-args: >-
            --file .binder/conda-lock.yml

      - name: Test environment
        run: >
          python -c 'import osgeo.gdal; print(dir(osgeo.gdal))'

      - name: Test links
        if: startsWith(matrix.os, 'ubuntu')
        run: >
          jupyter-book build jupyterbook --builder linkcheck
